<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');
/**
 * Generate Controller GC Config
 *
 *
 * Copyright (C) 2015 Gaëtan Cottrez.
 *
 *
 * @package    	Generate Controller GC
 * @copyright  	Copyright (c) 2015, Gaëtan Cottrez
 * @license 	GNU GENERAL PUBLIC LICENSE
 * @license 	http://www.gnu.org/licenses/gpl.txt GNU GENERAL PUBLIC LICENSE
 * @version    	1.0.0
 * @author 		Gaëtan Cottrez <gaetan.cottrez@laviedunwebdeveloper.com>
 */


// Config variables

$config['generate_controller_gc'] = array(
    // the name you want to appear on the copyright of the generated files
    'created_by' => 'Gaëtan Cottrez',
	// the name you want to appear on the copyright of the generated files
    'email_by' => 'gaetan.cottrez@laviedunwebdeveloper.com',
	// choice your default value theme (flexigrid/datatables/your theme maybe ?)
    'default_theme' => 'flexigrid',
	// path in folder view for load the output render generated by Grocery CRUD
    'render_view' => 'generate_controller_gc/list',
);



/* End of file generate_controller_gc.php */
/* Location: ./application/config/generate_controller_gc.php */